CCREATE TABLE IF NOT EXISTS STUDENT(
    ROLL_NUMBER TEXT PRIMARY KEY,
    NAME TEXT NOT NULL,
    ADDRESS TEXT,
    PHONE TEXT,
    AGE INTEGER
);


INSERT INTO STUDENT(ROLL_NUMBER,NAME,ADDRESS,PHONE,AGE) VALUES
    ('1','RAAJ','TAMILNADU','89256',14),
    ('2','HAMZA','PAKISTAN','65241',17),
    ('3','MINAKCHI MAM','UTTAR','68732',16),
    ('4','VAIDHAV','BENGALURU','63243',15),
    ('5','ALAN','ANDHRA','69437',13),
    ('6','YUVAN','KOLKATA','58655',14);
    
 SELECT * FROM STUDENT;
 
 SELECT * FROM STUDENT WHERE AGE =14 AND ADDRESS='TAMILNADU';